project:
  type: book
  output-dir: docs
  preview: 
    port: 4321


book:
  title: "Plano de Gestão FT - 2027-2030"
  subtitle: "Carmen & Vitor"
  date: "09/17/2026"
  chapters:
    - index.qmd
    - quem-somos.qmd
    - comunicacao.qmd
    - gestao.qmd
    - direitos-humanos.qmd
    - graduacao.qmd
    - pos-graduacao.qmd
    - pesquisa.qmd
    - extensao.qmd
    - infra.qmd
  navbar:
    search: false

format:
  html:
    fontsize: "1.3em"
    lang: pt
    page-layout: full
    theme: [flatly, custom.scss]
    css: 
       - styles.css
    toc: true
    number-sections: false